### ISSUE TITLE
Fails to run in 3151

### ISSUE THREAD

**Issue by weiweihuanghuang** [schriftgestalt/kernalytics-rf-ext#7]
```
A plugin caused a crash

The Plugin Kern-A-Lytics.glyphsFilter has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.

Details:
Traceback (most recent call last):

  File "plugin.py", line 22, in <module>
    from robofab.world import RFont

  File "world.py", line 29

    			raise RoboFabError, "We're running on an unknown platform."

    			                  ^

SyntaxError: invalid syntax

App:3.1.2-3151 Plugin:0.2-8
```

**Comment by schriftgestalt** [comment]
Can you remove and re-install the robofab module?

**Comment by weiweihuanghuang** [comment]
Works now!
